Repository Organizacja-Przestepcza/dev-work, pull requests merged in 2024-09, with the labels that each got.

#2 1 create api project
  .gitignore
  api/.gitignore
  api/Program.cs
  api/Properties/launchSettings.json
  api/api.csproj
  api/api.http
  api/appsettings.Development.json
  api/appsettings.json
Labels: feature

#17 feature/15-dtos
  api/Controllers/ChatController.cs
  api/Controllers/ChatsController.cs
  api/Controllers/MessageController.cs
  api/Controllers/MessagesController.cs
  api/Controllers/PostController.cs
  api/Controllers/PostsController.cs
  api/Controllers/UserController.cs
  api/Controllers/UsersController.cs
  api/Data/AppDbContext.cs
  api/Dtos/Bookmark/BookmarkRequestModel.cs
  api/Dtos/Bookmark/BookmarkResponseModel.cs
  api/Dtos/Chat/ChatRequestModel.cs
  api/Dtos/Chat/ChatResponseModel.cs
  api/Dtos/Connection/ConnectionRequestModel.cs
  api/Dtos/Connection/ConnectionResponseModel.cs
  api/Dtos/Member/MemberRequestModel.cs
  api/Dtos/Member/MemberResponseModel.cs
  api/Dtos/Message/MessageRequestModel.cs
  api/Dtos/Message/MessageResponseModel.cs
  api/Dtos/Post/PostRequestModel.cs
  api/Dtos/Post/PostResponseModel.cs
  api/Dtos/User/UserRequestModel.cs
  api/Dtos/User/UserResponseModel.cs
  api/Enums/Role.cs
  api/Mappers/BookmarkMappers.cs
  api/Mappers/ChatMappers.cs
  api/Mappers/ConnectionMappers.cs
  api/Mappers/MemberMappers.cs
  api/Mappers/MessageMappers.cs
  api/Mappers/PostMappers.cs
  api/Mappers/UserMappers.cs
  api/Migrations/20240906162059_InitialCreate.Designer.cs
  api/Migrations/AppDbContextModelSnapshot.cs
  api/Models/Member.cs
  api/Models/Message.cs
  api/Models/Post.cs
  api/Models/User.cs
  api/Program.cs
Labels: feature

#30 29 login buttons
  front-vue/pages/Login.vue
  front-vue/pages/Register.vue
  front-vue/pages/index.vue
Labels: feature

#33 32-mobile-layout
  front-vue/app.vue
  front-vue/layouts/mobile.vue
  front-vue/nuxt.config.ts
  front-vue/package-lock.json
  front-vue/package.json
  front-vue/pages/login.vue
  front-vue/pages/register.vue
Labels: feature

#31 21 default layout
  front-vue/layouts/default.vue
Labels: feature, in progress

#41 40 connect loginregister to front
  api/Program.cs
  front-vue/composables/useAuth.ts
  front-vue/nuxt.config.ts
  front-vue/pages/login.vue
  front-vue/pages/register.vue
Labels: type: feature, status: waiting

#52 Controller/Repo stuff
  api/Controllers/ChatController.cs
  api/Controllers/MessageController.cs
  api/Controllers/PostController.cs
  api/Controllers/UserController.cs
  api/Data/AppDbContext.cs
  api/Dtos/AppUser/UserDetailModel.cs
  api/Dtos/Bookmark/BookmarkRequestModel.cs
  api/Dtos/Bookmark/BookmarkResponseModel.cs
  api/Dtos/Chat/ChatRequestModel.cs
  api/Dtos/Chat/ChatResponseModel.cs
  api/Dtos/Chat/ChatUpdateModel.cs
  api/Dtos/ChatMember/ChatMemberRequestModel.cs
  api/Dtos/ChatMember/ChatMemberResponseModel.cs
  api/Dtos/ChatMember/ChatMemberUpdateModel.cs
  api/Dtos/Connection/ConnectionRequestModel.cs
  api/Dtos/Connection/ConnectionResponseModel.cs
  api/Dtos/Member/MemberRequestModel.cs
  api/Dtos/Member/MemberResponseModel.cs
  api/Dtos/Message/MessageUpdateModel.cs
  api/Dtos/Post/PostRequestModel.cs
  api/Dtos/Post/PostResponseModel.cs
  api/Dtos/Post/PostUpdateModel.cs
  api/Dtos/PostInteraction/PostInteractionRequestModel.cs
  api/Dtos/PostInteraction/PostInteractionResponseModel.cs
  api/Dtos/PostInteraction/PostInteractionUpdateModel.cs
  api/Interfaces/IBookmarkRepository.cs
  api/Interfaces/IConnectionRepository.cs
  api/Interfaces/IMemberRepository.cs
  api/Interfaces/IPostInteractionRepository.cs
  api/Mappers/BookmarkMappers.cs
  api/Mappers/ConnectionMappers.cs
  api/Mappers/MemberMappers.cs
  api/Mappers/PostInteractionMappers.cs
  api/Mappers/PostMappers.cs
  api/Models/Bookmark.cs
  api/Models/Chat.cs
  api/Models/Post.cs
  api/Repositories/BookmarkRepository.cs
  api/Repositories/ChatRepository.cs
  api/Repositories/ConnectionRepository.cs
  api/Repositories/MemberRepository.cs
  api/Repositories/PostInteractionRepository.cs
Labels: type: enhancement, status: waiting

#54 28 home page
  front-vue/common/models.ts
  front-vue/components/ChatTile/index.vue
  front-vue/components/ContactTile/index.vue
  front-vue/components/Login/index.vue
  front-vue/components/Post/index.vue
  front-vue/components/PostFilterPanel/index.vue
  front-vue/composables/useAuth.ts
  front-vue/layouts/default.vue
  front-vue/nuxt.config.ts
  front-vue/package-lock.json
  front-vue/package.json
  front-vue/pages/home.vue
  front-vue/pages/login.vue
Labels: type: enhancement, status: waiting

#58 Data validation and authorization
  api/Controllers/AccountController.cs
  api/Controllers/BookmarkController.cs
  api/Controllers/ChatController.cs
  api/Controllers/ConnectionController.cs
  api/Controllers/MessageController.cs
  api/Controllers/PostController.cs
  api/Controllers/UserController.cs
  api/Data/AppDbContext.cs
  api/Dtos/Account/RegisterRequestModel.cs
  api/Dtos/AppUser/UserResponseModel.cs
  api/Dtos/AppUser/UserUpdateModel.cs
  api/Dtos/Bookmark/BookmarkRequestModel.cs
  api/Dtos/Bookmark/BookmarkResponseModel.cs
  api/Dtos/Chat/ChatRequestModel.cs
  api/Dtos/Chat/ChatUpdateModel.cs
  api/Dtos/Connection/ConnectionRequestModel.cs
  api/Dtos/Connection/ConnectionResponseModel.cs
  api/Dtos/Message/MessageRequestModel.cs
  api/Dtos/Message/MessageResponseModel.cs
  api/Dtos/Message/MessageUpdateModel.cs
  api/Dtos/Post/PostRequestModel.cs
  api/Dtos/Post/PostResponseModel.cs
  api/Dtos/Post/PostUpdateModel.cs
  api/Dtos/PostInteraction/PostInteractionUpdateModel.cs
  api/Dtos/TokenData.cs
  api/Helpers/CurrentUserMethods.cs
  api/Helpers/PaginationQuery.cs
  api/Interfaces/IBookmarkRepository.cs
  api/Interfaces/IChatRepository.cs
  api/Interfaces/IConnectionRepository.cs
  api/Interfaces/IMemberRepository.cs
  api/Interfaces/IMessageRepository.cs
  api/Interfaces/IPostRepository.cs
  api/Interfaces/ITokenService.cs
  api/Mappers/BookmarkMappers.cs
  api/Mappers/ConnectionMappers.cs
  api/Mappers/MessageMappers.cs
  api/Mappers/PostInteractionMappers.cs
  api/Mappers/PostMappers.cs
  api/Mappers/UserMappers.cs
  api/Models/AppUser.cs
  api/Models/Bookmark.cs
  api/Models/Chat.cs
  api/Models/ChatMember.cs
  api/Models/Connection.cs
  api/Models/Message.cs
  api/Models/Post.cs
  api/Models/PostInteraction.cs
  api/Repositories/BookmarkRepository.cs
  api/Repositories/ChatRepository.cs
  api/Repositories/ConnectionRepository.cs
  api/Repositories/MemberRepository.cs
  api/Repositories/MessageRepository.cs
  api/Repositories/PostInteractionRepository.cs
  api/Repositories/PostRepository.cs
  api/Service/TokenService.cs
Labels: type: enhancement, status: in progress
